modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Template"
authors = "Me!"
description = "This is an example description! Tell everyone what your mod is about!"
logoFile = "assets/${mod_id}/icon.png"
logoBlur = false

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"