@file:Suppress("UnstableApiUsage")

import net.fabricmc.loom.task.RemapJarTask
import org.gradle.kotlin.dsl.support.serviceOf
import org.jetbrains.gradle.ext.packagePrefix
import org.jetbrains.gradle.ext.settings


plugins {
	java
	idea
	alias(libs.plugins.ideaExt)
	alias(libs.plugins.shadow)
	alias(libs.plugins.architecturyPlugin)
	alias(libs.plugins.architecturyLoom)
	alias(libs.plugins.forgix)
}

// Transfer all properties from settings to projects
allprojects {
	rootProject.gradle.extra.properties.forEach { (key, value) ->
		project.ext.set(key, value)
	}
}

// Create build.properties file for pre-processor
fun createBuildProperties() {
	val builder = StringBuilder()
	builder.appendLine("# DON'T MODIFY THIS FILE!")
	builder.appendLine("# This file is automatically generated")

	val mcVersions: List<String> by extra
	val mcIndex: Int by extra

	mcVersions.forEachIndexed { index, version ->
		builder.appendLine("MC_${version.replace(".", "_")} = $index")
		if (index == mcIndex) builder.appendLine("MC_VER = $mcIndex")
	}

	File(rootDir, "build.properties").writeText(builder.toString())
}
createBuildProperties()

val javaVersion: String by extra
val mcVersion: String by extra
val buildFor: String by extra

val modVersion: String by extra
val modGroup: String by extra
val modId: String by extra

val modName: String by extra
val modDescription: String by extra
val modAuthors: String by extra
val modLicense: String by extra

val parchmentMinecraftVersion: String by extra
val parchmentMappingVersion: String by extra
val fabricLoaderVersion: String? by extra
val neoforgeLoaderVersion: String? by extra
val forgeLoaderVersion: String? by extra

architectury {
	minecraft = mcVersion
	common(buildFor.split(","))
}

allprojects {
	apply(plugin = "java")
	apply(plugin = "idea")
	apply(plugin = rootProject.libs.plugins.ideaExt.get().pluginId)
	apply(plugin = rootProject.libs.plugins.shadow.get().pluginId)
	apply(plugin = rootProject.libs.plugins.architecturyPlugin.get().pluginId)
	apply(plugin = rootProject.libs.plugins.architecturyLoom.get().pluginId)

	version = "$modVersion+$mcVersion"
	group = modGroup

	loom {
		silentMojangMappingsLicense()
		accessWidenerPath = rootProject.file("src/main/resources/$modId.accesswidener")

		runs {
			val runDir = "../.runs"

			named("client") {
				client()
				configName = "Client"
				runDir("$runDir/client")
				programArgs("--username=Dev")
			}
			named("server") {
				server()
				configName = "Server"
				runDir("$runDir/server")
			}
		}

		runs.all {
			ideConfigGenerated(false)
		}

		decompilers {
			get("vineflower").apply { // Shows the method name of lambdas in a comment
				options.put("mark-corresponding-synthetics", "1")
			}
		}
	}

	repositories {
		maven("https://maven.parchmentmc.org/")
	}

	dependencies {
		minecraft("com.mojang:minecraft:$mcVersion")
		mappings(loom.layered {
			officialMojangMappings()
			parchment("org.parchmentmc.data:parchment-$parchmentMinecraftVersion:$parchmentMappingVersion@zip")
		})
		modImplementation("net.fabricmc:fabric-loader:$fabricLoaderVersion")

		annotationProcessor(rootProject.libs.preprocessor)
	}

	java {
		withSourcesJar()
		val java = JavaVersion.toVersion(javaVersion)
		targetCompatibility = java
		sourceCompatibility = java
	}

	tasks {
		withType(JavaCompile::class) {
			options.compilerArgs.add("-Xplugin:Manifold")
		}

		test {
			enabled = false
		}

		compileTestJava {
			enabled = false
		}
	}

	idea {
		module {
			settings {
				val packagePrefixStr = "${project.group}.${rootProject.name.lowercase()}".let {
					if (rootProject != project) "$it.${project.name.lowercase()}" else it
				}
				packagePrefix["src/main/java"] = packagePrefixStr
			}
		}
	}
}

subprojects {
	val common: Configuration by configurations.creating {
		isCanBeResolved = true
		isCanBeConsumed = false
	}
	configurations.compileClasspath.get().extendsFrom(common)
	configurations.runtimeClasspath.get().extendsFrom(common)

	val commonShadow: Configuration by configurations.creating {
		isCanBeResolved = true
		isCanBeConsumed = false
	}

	loom.runs.all {
		ideConfigGenerated(true)
	}

	tasks {
		processResources {
			val props = mutableMapOf(
				"java_version" to javaVersion,
				"minecraft_version" to mcVersion,

				"mod_version" to modVersion,
				"mod_group" to modGroup,
				"mod_id" to modId,

				"mod_name" to modName,
				"mod_description" to modDescription,
				"mod_license" to modLicense,
				"mod_authors_fabric" to modAuthors.split(",").joinToString(", ") { "\"$it\"" },
				"mod_authors_forge" to modAuthors,
			)

			if (project.name == "fabric") props["fabric_loader_version"] = fabricLoaderVersion ?: ""
			if (project.name == "neoforge") props["neoforge_loader_version"] = neoforgeLoaderVersion ?: ""
			if (project.name == "forge") props["forge_loader_version"] = forgeLoaderVersion ?: ""

			inputs.properties(props)
			filesMatching(listOf("META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json", "**.mixins.json", "pack.mcmeta")) {
				expand(props)
			}
		}

		remapJar {
			inputFile = shadowJar.get().archiveFile
			injectAccessWidener = true
		}

		shadowJar {
			configurations = listOf(commonShadow)
			archiveClassifier.set("dev-shadow")
			exclude("architectury.common.json")
		}
	}
}

evaluationDependsOnChildren()

forgix {
	archiveClassifier = ""

	fabric {
		inputJar = project(":fabric").tasks.named<RemapJarTask>("remapJar").get().archiveFile
	}

	neoforge {
		inputJar = project(":neoforge").tasks.named<RemapJarTask>("remapJar").get().archiveFile
	}

	multiversion {
		destinationDirectory
		archiveVersion = modVersion

		val versions =  file("versionProperties").listFiles { file ->
			file.isFile && file.extension == "properties"
		}!!.map { file -> file.nameWithoutExtension }

		inputJars = project.files(
			versions.map { version -> "build/forgix/${rootProject.name}-$modVersion+$version.jar" }
		)
	}
}

tasks.register("buildAllVersions") {
	group = "build"
	description = "Build for all Minecraft versions found in versionProperties folder"
	dependsOn("clean")
	finalizedBy("mergeVersions")

	doLast {
		val versionsFolder = file("versionProperties")
		var successCount = 0
		var failedCount = 0
		val failedVersions = mutableListOf<String>()

		logger.lifecycle("Starting build process for all Minecraft versions...\n")

		if (!versionsFolder.exists()) 
			throw GradleException("Error: Versions folder 'versionProperties' not found!")

		val propertiesFiles = versionsFolder.listFiles { file ->
			file.isFile && file.extension == "properties"
		}.toList()

		if (propertiesFiles.isEmpty()) {
			logger.lifecycle("No .properties files found in versionProperties folder")
			return@doLast
		}

		val execOps = project.serviceOf<ExecOperations>()
		for (propertiesFile in propertiesFiles) {
			val filename = propertiesFile.nameWithoutExtension

			logger.lifecycle("Building for Minecraft version: $filename")
			logger.lifecycle("Using properties file: ${propertiesFile.absolutePath}")

			try {
				val buildResult = execOps.exec {
					if (System.getProperty("os.name").lowercase().contains("windows")) {
						commandLine("cmd", "/c", "gradlew.bat", "build", "mergeJars", "-PmcVersion=$filename")
					} else {
						commandLine("./gradlew", "build", "mergeJars", "-PmcVersion=$filename")
					}
					isIgnoreExitValue = true
				}

				if (buildResult.exitValue == 0) {
					logger.lifecycle("Successfully built for version $filename")
					successCount++
				} else {
					logger.lifecycle("Failed to build for version $filename")
					failedCount++
					failedVersions.add(filename)
				}
			} catch (e: Exception) {
				logger.lifecycle("Failed to build for version $filename: ${e.message}")
				failedCount++
				failedVersions.add(filename)
			}

			logger.lifecycle("----------------------------------------")
		}

		logger.lifecycle("\nBuild Summary:")
		logger.lifecycle("Successful builds: $successCount")
		logger.lifecycle("Failed builds: $failedCount")

		if (failedCount > 0) {
			logger.lifecycle("Failed versions: ${failedVersions.joinToString(", ")}")
			throw GradleException("$failedCount build(s) failed")
		} else {
			logger.lifecycle("All builds completed successfully!")
		}
	}
}