@file:Suppress("UnstableApiUsage")

import net.fabricmc.loom.task.RemapJarTask
import org.jetbrains.gradle.ext.packagePrefix
import org.jetbrains.gradle.ext.settings


plugins {
	java
	idea
	alias(libs.plugins.ideaExt)
	alias(libs.plugins.shadow)

	alias(libs.plugins.neoforgeModdev)
	alias(libs.plugins.fabricLoom) apply false
	alias(libs.plugins.forgix)
}

// Transfer all properties from settings to projects
allprojects {
	rootProject.gradle.extra.properties.forEach { (key, value) ->
		project.ext.set(key, value)
	}
}

// Create build.properties file for pre-processor
fun createBuildProperties() {
	val builder = StringBuilder()
	builder.appendLine("# DON'T MODIFY THIS FILE!")
	builder.appendLine("# This file is automatically generated")

	val mcVersions: List<String> by extra
	val mcIndex: Int by extra

	mcVersions.forEachIndexed { index, version ->
		builder.appendLine("MC_${version.replace(".", "_")} = $index")
		if (index == mcIndex) builder.appendLine("MC_VER = $mcIndex")
	}

	File(rootDir, "build.properties").writeText(builder.toString())
}
createBuildProperties()

val mcVersion: String by extra

val modVersion: String by extra
val modGroup: String by extra
val modId: String by extra

val modName: String by extra
val modDescription: String by extra
val modAuthors: String by extra
val modLicense: String by extra

val parchmentMinecraftVersion: String by extra
val parchmentMappingVersion: String by extra
val fabricLoaderVersion: String by extra
val neoforgeLoaderVersion: String by extra
val neoformVersion: String by extra

neoForge {
	neoFormVersion = neoformVersion

	validateAccessTransformers = true

	parchment {
		minecraftVersion = parchmentMinecraftVersion
		mappingsVersion = parchmentMappingVersion
	}
}

repositories {
	maven("https://repo.spongepowered.org/repository/maven-public/")
}

dependencies {
	compileOnly("org.spongepowered:mixin:0.8.5:processor")
	compileOnly("io.github.llamalad7:mixinextras-common:0.3.5")
	annotationProcessor("io.github.llamalad7:mixinextras-common:0.3.5")
}

allprojects {
	apply(plugin = "java")
	apply(plugin = "idea")
	apply(plugin = "org.jetbrains.gradle.plugin.idea-ext")
	apply(plugin = rootProject.libs.plugins.ideaExt.get().pluginId)
	apply(plugin = rootProject.libs.plugins.shadow.get().pluginId)

	version = "$modVersion+$mcVersion"
	group = modGroup

	repositories {
		maven("https://maven.parchmentmc.org/")
	}

	dependencies {
		annotationProcessor(rootProject.libs.preprocessor)
	}

	java {
		withSourcesJar()
		val java = JavaVersion.VERSION_21
		targetCompatibility = java
		sourceCompatibility = java
	}

	tasks {
		withType(JavaCompile::class) {
			options.compilerArgs.add("-Xplugin:Manifold")
		}

		test {
			enabled = false
		}

		compileTestJava {
			enabled = false
		}

	}

	idea {
		module {
			settings {
				val packagePrefixStr = "${project.group}.${rootProject.name.lowercase()}".let {
					if (rootProject != project) "$it.${project.name.lowercase()}" else it
				}
				packagePrefix["src/main/java"] = packagePrefixStr
			}
		}
	}
}

subprojects {
	val common: Configuration by configurations.creating {
		isCanBeResolved = true
		isCanBeConsumed = false
	}
	configurations.compileClasspath.get().extendsFrom(common)
	configurations.runtimeClasspath.get().extendsFrom(common)

	val commonShadow: Configuration by configurations.creating {
		isCanBeResolved = true
		isCanBeConsumed = false
	}

	dependencies {
		common(project(":"))
		commonShadow(project(":"))
	}

	tasks {
		processResources {
			val props = mutableMapOf(
				"minecraft_version" to mcVersion,

				"mod_version" to modVersion,
				"mod_group" to modGroup,
				"mod_id" to modId,

				"mod_name" to modName,
				"mod_description" to modDescription,
				"mod_license" to modLicense,
				"mod_authors_fabric" to modAuthors.split(",").joinToString(", ") { "\"$it\"" },
				"mod_authors_forge" to modAuthors,
			)

			if (project.name == "fabric") props["fabric_loader_version"] = fabricLoaderVersion
			if (project.name == "neoforge") props["neoforge_loader_version"] = neoforgeLoaderVersion

			inputs.properties(props)
			filesMatching(listOf("META-INF/neoforge.mods.toml", "fabric.mod.json", "*.mixin.json", "pack.mcmeta")) {
				expand(props)
			}
		}

		shadowJar {
			configurations = listOf(commonShadow)
		}
	}
}

evaluationDependsOnChildren()

forgix {
	fabric {
		inputJar = project(":fabric").tasks.named<RemapJarTask>("remapJar").get().archiveFile
	}

	neoforge {
		inputJar = project(":neoforge").tasks.shadowJar.get().archiveFile
	}

	autoRun = true

	multiversion {
		inputJars = project.files(
			"build/forgix/Template-0.1.0+1.21.8-fabric-neoforge.jar",
			"build/forgix/Template-0.1.0+1.21.7-fabric-neoforge.jar",
			"build/forgix/Template-0.1.0+1.21.6-fabric-neoforge.jar"
		)
	}
}