org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
fabric.loom.multiProjectOptimisation = true

modVersion = 1.0.0
modId = template
modGroup = com.example

modName = Template
modDescription = This is an example description! Tell everyone what your mod is about!
modAuthors = John Doe
modLicense = MIT

### Mod properties ###
mod.version = 0.1.0
mod.group = com.example
mod.id = template

mod.name = Template
mod.description = This is an example description! Tell everyone what your mod is about!
mod.license = MIT