buildFor = fabric,neoforge

# Loader versions
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 21.8.4-beta
neoformVersion = 1.21.8-20250717.133445

# Parchment mapping
parchmentMinecraftVersion = 1.21.6
parchmentMappingVersion = 2025.06.29