buildFor = fabric,neoforge

# Loader versions
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 21.6.20-beta

# Parchment mapping
parchmentMinecraftVersion = 1.21.6
parchmentMappingVersion = 2025.06.29