buildFor = fabric,neoforge
javaVersion = 21

# Loader versionProperties
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 20.5.21-beta

# Parchment mapping
parchmentMinecraftVersion = 1.20.6
parchmentMappingVersion = 2024.06.16