buildFor = fabric,neoforge
javaVersion = 21

# Loader versionProperties
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 21.0.167

# Parchment mapping
parchmentMinecraftVersion = 1.21.1
parchmentMappingVersion = 2024.1.17