buildFor = fabric,neoforge
javaVersion = 21

# Loader versionProperties
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 21.2.1-beta

# Parchment mapping
parchmentMinecraftVersion = 1.21.3
parchmentMappingVersion = 2024.12.07