buildFor = fabric,neoforge
javaVersion = 21

# Loader versionProperties
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 21.8.25

# Parchment mapping
parchmentMinecraftVersion = 1.21.8
parchmentMappingVersion = 2025.07.20