buildFor = fabric,neoforge
javaVersion = 21

# Loader versionProperties
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 21.4.148

# Parchment mapping
parchmentMinecraftVersion = 1.21.4
parchmentMappingVersion = 2025.03.23