buildFor = fabric,neoforge

# Loader versionProperties
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 21.7.25-beta

# Parchment mapping
parchmentMinecraftVersion = 1.21.7
parchmentMappingVersion = 2025.07.18